### ISSUE TITLE
Not all pixel values defined

### ISSUE THREAD

**Issue by netmindz** [StefanPetrick/animartrix#23]
If you swap between effects, you get odd issues with the "dirty" state of the RGB pixel

See 
https://github.com/netmindz/animartrix/commit/8fd0df3e0b006244d53eaf480c2720daa5a697aa

**Comment by StefanPetrick** [comment]
Yep, in the original design, I didn't consider changing effects on the fly. It will be addressed in the next release (which might very well become a complete refactoring...)
